services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: aplicacion.dockerfile
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:
    build:
      context: ./dockerfiles
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    ports:
      - 8080:80
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"
volumes:
  dbdata: