services:
    www:
        build: 
            context: ./
            dockerfile: ./dockerfiles/Dockerfile.web
        container_name: apache-laravel
        ports: 
            - "8001:80"
        volumes:
            - ./web/app:/var/www/html
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
        links:
            - db
        networks:
            - red-laravel
    db:
        image: mysql:8
        container_name: mysql-laravel
        ports: 
            - "33306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${USUARIO_MYSQL}
            MYSQL_PASSWORD: ${PASSWORD_USUARIO_MYSQL}
            MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MYSQL}
        volumes:
            - persistente:/var/lib/mysql
        networks:
            - red-laravel
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-laravel
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: ${USUARIO_MYSQL}
            MYSQL_PASSWORD: ${PASSWORD_USUARIO_MYSQL}
            MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MYSQL}
        networks:
            - red-laravel
volumes:
    persistente:

networks:
    red-laravel: