services:
  # mysql-workbench:
  #   image: lscr.io/linuxserver/mysql-workbench:latest
  #   container_name: mysql-workbench
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /path/to/config:/config
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #   cap_add:
  #     - IPC_LOCK
  #   restart: unless-stopped

  base-datos:
      image: mysql:8.0
      container_name: mysql
      ports: 
          - "33306:3306"
      environment:
          MYSQL_DATABASE: ${MYSQL_DB}
          MYSQL_USER: ${USUARIO_MYSQL}
          MYSQL_PASSWORD: ${PASSWORD_USUARIO_MYSQL}
          MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MYSQL}
      volumes:
          - persistente:/var/lib/mysql
      networks:
        - redBBDD

  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-mysql
        ports:
            - 8000:80
        environment:
            MYSQL_USER: ${USUARIO_MYSQL}
            MYSQL_PASSWORD: ${PASSWORD_USUARIO_MYSQL}
            MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MYSQL}
            PMA_HOST: mysql
        networks:
          - redBBDD

volumes:
    persistente:

networks:
    redBBDD: 